services:
  #develop:
  #  container_name: demo_app
  #  build: .
  #  environment:
  #    DB_HOST: database
  #    DB_PORT: 3306
  #    DB_USERNAME: develop
  #    DB_PASSWORD: develop2023
  #    DB_NAME: multiservicios_db
  #  ports:
  #    - "3000:3000"
  #  restart: always
  #  networks:
  #    - demo-app-network
  database:
    container_name: mysql_database
    image: mysql:8.0.34
    environment:
      MYSQL_ROOT_PASSWORD: emprendimiento2023
      MYSQL_USER: develop
      MYSQL_PASSWORD: develop2023
      MYSQL_DATABASE: multiservicios_db
    ports:
      - "3306:3306"
    restart: always
    networks:
      - demo-app-network
  phpmyadmin:
    container_name: php_my_admin
    image: phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - 8080:80
    restart: always
    networks:
      - demo-app-network     
networks:
  demo-app-network:
    driver: bridge